### ISSUE TITLE
Positional parameter missing

### ISSUE THREAD

**Issue by klashagel** [jamie-davis/ConsoleTools#12]
Hi , i have a command defined , like this

```
    [Keyword("log")]
    [InteractiveCommand("add")]
    [Description("Add a log job for controller")]
    public class AddLogCommand
    {
        [Positional(DefaultValue = "10.14.214.50")]
        [Description("IP adress of controller , ex 192.168.0.21")]
        public string ip { get; set; }

        [Positional(DefaultValue = "tags.csv")]
        [Description("Tag file to be polled , ex epictags.csv")]
        public string tagfile { get; set; }

        [Positional(DefaultValue = "1000")]
        [Description("Polling with interval in milliseconds, ex 1000 ")]
        public int interval { get; set; }

        [Positional(DefaultValue = ";")]
        [Description("Delimiter in log file")]
        public string delim { get; set; }

        [CommandHandler]
        public void Handle(IConsoleAdapter console, IErrorAdapter error)
        {
            console.WrapLine("Polling to \"{0}\".", ip);
            Controller ctrl = new Controller(ip);
            ctrl.PollController(tagfile, interval,delim);

        }
    }
```
The command generates a csv file with the delimiter in the parameter `delim`
When entering the command in the console application , below works

```
log add 192.168.0.10 tags.csv 1000 -delim :
log add 192.168.0.10 tags.csv 1000 : 
log add 192.168.0.10 tags.csv 1000 ,
```

but when specifying the delim parameter with a[ ,](url) char as below
```
log add 192.168.0.10 tags.csv 1000 -delim ,
```
the parameter is empty , any suggestions

**Comment by jamie-davis** [comment]
I think this is a bug. In the Microsoft Standard conventions parser, it tries to extract "option parameters", and uses this conditional to decide whether to split the argument into parameters:

`if ((option == null || (option.ParameterCount > 0 && argQueue.Count > 0)) && (argQueue.Count > 0 && !argQueue.Peek().StartsWith("-")))`

Here, "option == null" will be true, because this is a positional parameter. If it was an option, it would know whether to split on commas because of the parameter count, but I think I am accidentally assuming that all named positionals need multiple parameters, whereas I think I intended the opposite.

I think the fix is probably:

`if ((option != null && (option.ParameterCount > 0 && argQueue.Count > 0)) && (argQueue.Count > 0 && !argQueue.Peek().StartsWith("-")))`

I can't try it at the moment, so I'll have to look at it tonight.

**Comment by jamie-davis** [comment]
That wasn't quite it - it was the same problem but on the next line. This is the fixed version:

`arguments = option != null && option.ParameterCount > 1 ? argQueue.Dequeue().Split(',') : new []{ argQueue.Dequeue() };`

I've released a new nuget package with the fix.

Could you let me know if it fixes your problem?

Thanks,
Jamie.

**Comment by jamie-davis** [comment]
I've not heard to the contrary, so I'm going to assume the release solved the problem and close this issue.
