### ISSUE TITLE
Interactive console?

### ISSUE THREAD

**Issue by globeport** [jamie-davis/ConsoleTools#9]
Hi thanks for putting this library together.

I've just had a quick skirt over the documentation. I'd like to put together an interactive console that maintains some state between commands. Is there any way of launching the console in interactive mode so that commands can be input one after the other within the same process?

**Comment by jamie-davis** [comment]
This is not currently possible, but it is a feature I would like to implement. I think most of the components needed to support it are already available in the library, but the code that executes commands is private to the `CommandDrivenApplication` base class, so it's not possible to bolt the feature on from the outside.

I'll see if I can find some time to work on it - give me a few days and check back.

**Comment by jamie-davis** [comment]
My thoughts on this are as follows:

The interactive "session" will be managed by the framework, and you will access the feature by requesting an "`IInteractiveSessionService`" interface in your command handler. This will be an injectable interface in the same vein as `IConsoleAdapter `and `IErrorAdapter`.

`IInteractiveSessionService `will have two methods:

```
public interface IInteractiveSessionService
{
	/* Start an interactive session in which the user can enter commands for which the handler will run immediately. /*
	void BeginSession();

	/* Exit the current interactive session. */
	void EndSession();
}

```
The idea is that you will implement at least two commands. One will be a command that starts the interactive session, and it will call "`BeginSession()`". The other command will be an exit command that calls "`EndSession()`" which will tell the service that the session is over.

For example:

```
[Command]
class InteractiveCommand
{
	[CommandHandler]
	public void Handle(IInteractiveSessionService interactiveSessionService)
	{
		interactiveSessionService.BeginSession();
	}

}


[Command]
class ExitCommand
{
	[CommandHandler]
	public void Handle(IInteractiveSessionService interactiveSessionService)
	{
		interactiveSessionService.EndSession();
	}

}
```

Therefore, given the above, to initiate an interactive session the user would call the application with the "interactive" command. They would then be able to issue any of the application's useful commands until they use the "exit" command which would end the session and the executable.

There are likely to be more members on the "`IInteractiveSessionService`", for example, to allow you to determine whether an interactive session is in progress, and to allow control of the prompt displayed to the user.

I'm going to proceed on this basis, but all feedback is welcome and will be considered.

**Comment by globeport** [comment]
Looks good. If would also be nice to be able to start an application with interactive mode as the default (or only mode) - without having to call the application with an interactive command.

**Comment by jamie-davis** [comment]
I thought about that. I could add a `[DefaultCommand] `attribute, and this would label a command as the one to run if there are no command line parameters. Obviously it would be an error for you to put `[DefaultCommand]` on a command with mandatory positional parameters, but the command could still have options. I need to think carefully about this, but if there is no command on the command line, any options could be considered options for the default command. It's not 100% clear to me that there are no problem cases that would cause issues.

As an example:

```
[DefaultCommand]
class InteractiveCommand
{
	[Option("username", "u")]
	public string Username {get; set; }

	[Option("username", "p")]
	public string Username {get; set; }

	[CommandHandler]
	public void Handle(IInteractiveSessionService interactiveSessionService)
	{
		if (Authenticate())
			interactiveSessionService.BeginSession();
	}

	private bool Authenticate()
	{
		//authenticate using the supplied username and password if present
		...
	}
}

```		
Assuming the application is called example.exe, consider these command lines:

`	C:\>example
`
This would invoke "interactive" with null Username and Password

`	C:\>example -u jamie`

This would invoke "interactive" with Username set to "jamie" and password set to null.

`	C:\>example -u jamie -p Password1`

You get the idea.

This would be an error:

`	C:\>example jamie`

This would look like the user was attempting to invoke the "jamie" command because there is no option introducer. Alternatively, if there were a "jamie" command, it would actually invoke that command. The only scenario in which the default command would be invoked would be when there are zero or more options and no positional parameters.

What's not clear to me is whether or not using the MicrosoftStandard parsing conventions would allow a command with positional parameters to be the default command. While you could supply the parameters on the command line, it pretty much defeats the object, so I may disallow it.

**Comment by jamie-davis** [comment]
Actually, I've change my mind about the `[DefaultCommand]` idea, because you can already build an application with a default command - it's a `ConsoleApplication`.

Instead of `[DefaultCommand]`, a `ConsoleApplication `should accept (this is the case now) a single `[Command]` and any number of `[InteractiveCommand]` types.

Everything else stays the same, including the `InteractiveCommand` class from my previous post.

`[InteractiveCommand]` types will only be valid in interactive sessions. The opposite will be `[NonInteractiveCommand]` types which will not be valid in interactive sessions.

**Comment by globeport** [comment]
perfect!

**Comment by jamie-davis** [comment]
I've put a pre-release package on nuget if you want to give it a try. It supports the interactive session in a `CommandDrivenApplication`, but that's about it so far. Next I'm going to add:

1. Prompt support. You should be able to specify a command prompt string at any time. This will be valid even if there is no interactive session in progress.
2. Different command types - `[InteractiveCommand]` and `[NonInteractiveCommand]`
3. Help support. The existing help text should only display commands valid outside an interactive session. The help within an interactive session should only display commands valid within the interactive session. A `ConsoleApplication` needs to be able to specify a help command for within an interactive session.

**Comment by jamie-davis** [comment]
A second pre-release package is up on nuget. This one allows a `ConsoleApplication` to run an interactive session like this:

```
    class Program : ConsoleApplication
    {
        static void Main(string[] args)
        {
            Toolkit.Execute<Program>(args);
        }

        #region Overrides of ConsoleApplicationBase

        protected override void Initialise()
        {
            HelpOption<Options>(o => o.Help);
            base.Initialise();
        }

        #endregion
    }

    [Command]
    [Description("A demo of an interactive only console application.")]
    public class Options
    {
        [Option("h")]
        [Description("Display help text")]
        public bool Help { get; set; }

        [CommandHandler]
        public void Handle(IInteractiveSessionService service)
        {
            service.SetPrompt("-->");
            service.BeginSession();
        }
    }

    [InteractiveCommand]
    [Description("List directories")]
    public class DirCommand
    {
        [Positional(".")]
        [Description("Optional path to list.")]
        public string Path { get; set; }

        [CommandHandler]
        public void Handle(IConsoleAdapter console, IErrorAdapter error)
        {

            console.FormatTable(Directory.EnumerateDirectories(Path).Select(d => new { Directory = d }));
        }
    }

    [InteractiveCommand]
    [Description("End the interactive session.")]
    public class ExitCommand
    {
        [CommandHandler]
        public void Handle(IInteractiveSessionService service)
        {
            service.EndSession();
        }
    }

```

**Comment by jamie-davis** [comment]
These changes have been released as 1.2.0 of the library.

**Comment by jamie-davis** [comment]
Documentation updated.

**Comment by globeport** [comment]
Thankyou!

**Comment by jamie-davis** [comment]
You're welcome :)
